FROM python:latest

WORKDIR /container_app

RUN pip install poetry

COPY ./app /container_app

RUN poetry config virtualenvs.create false && poetry install

CMD ["poetry","run","python","-m","pytest"]